name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CHANGELOG.org -> CHANGELOG.md
        uses: docker://pandoc/core:2.9
        with:
          args: -s CHANGELOG.org -t gfm -o docs/page/CHANGELOG.md

      - uses: purcell/setup-emacs@master
        with:
          version: 27.1

      - uses: conao3/setup-cask@master
        with:
          version: 0.8.4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material \
          mkdocs-awesome-pages-plugin>=2.2.1 \
          mkdocs-git-revision-date-localized-plugin>=0.4 \
          mkdocs-minify-plugin>=0.3 \
          mkdocs-redirects>=1.0 \
          mkdocs-rss-plugin>=0.6.1

      - name: Generate LSPs docs
        run: 'make docs'

      - name: MkDocs
        run: |
          cp -rf README.md examples docs

          mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
